### ISSUE TITLE
this._domObserver.disconnect is not a function.

### ISSUE THREAD

**Issue by paszkowskiDamian** [w3c/IntersectionObserver#346] opened 2019-02-12 13:42 UTC
I'm using this lib as polyfill and seams as it failing in some cases. The errors I get are only from Bugsnag I cannot reproduce it on my device. 

Error message:
```
this._domObserver.disconnect is not a function. (In 'this._domObserver.disconnect()', 'this._domObserver.disconnect' is undefined)
```

Stacktrace: 
![image](https://user-images.githubusercontent.com/15217169/52639190-08f92180-2ed4-11e9-940e-2ea22220d25f.png)

Browser:
- only Safari 11.

Does anyone have any idea at least how to reproduce it?

**Comment by bjornbos** [comment] 2019-02-19 08:51
I'm seeing the same errors in our Bugsnag account. Also limited to Safari 11.

**Comment by philipwalton** [comment] 2019-04-24 19:01
This is very surprising to me. The line directly above that checks for the presence of `this._domObserver`, and I don't see how that could exist but not have a `disconnect()` method.

I also can't reproduce the error when running the tests on Safari 11 (iOS) or Safari 11.1 (10.13). I'm going to close this issue since I can't reproduce it, but if anyone can, feel free to reply below.

**Closed by philipwalton** 2019-04-24 19:01 UTC

**Comment by santosch** [comment] 2019-07-25 07:43
I can confirm this issue.
Perhaps the mutation observer needs to be polyfilled as well? But this issue seems to be rather uncommon.
