### ISSUE TITLE
Intersection Observer Api new feature request

### ISSUE THREAD

**Issue by cnsndnz** [w3c/IntersectionObserver#489] opened 2021-11-20 21:50 UTC
Hello,

This is a feature request for intersection observer api and this feature can be provided as optional via options parameter if it is possible. It is important that the measuring the correct 'viewability' of an ad in online advertisement business. If the intersection observer api can takes into account the browser position and status it will be better for use of advertising purposes. For example Intersection Observer Api can trigger visibility change events for the target element;

- When you dragged out the browser and dragged in again in to the screen
- When you minimize or maximize the screen.

Thanks

**Comment by miketaylr** [comment] 2022-06-09 20:19
@cnsndnz could clarify what the feature request is here? Are you asking for IntersectionObserver to provide info outside of the browser window (i.e. window state relative to the screen)? Or something else?

**Comment by miketaylr** [comment] 2022-06-09 23:13
Thanks - that sounds exactly like what https://github.com/w3c/IntersectionObserver/issues/471 is proposing as well. Let's close this one as a dupe of the earlier one.

**Closed by miketaylr** 2022-06-09 23:13 UTC
Labels: enhancement
