### ISSUE TITLE
Polyfill not working on iOS

### ISSUE THREAD

**Issue by dsozzi** [w3c/IntersectionObserver#315] opened 2018-09-07 07:38 UTC
I'm running the polyfill inside a cordova app and, when scrolling, the intersection callback is not fired. If I scroll moving my finger on the device without releasing it, the callback is fired correctly. I've tried setting the `POLL_INTERVAL` as described in the doc but it wont' work.
One small note: I'm using the `-webkit-overflow-scrolling: touch` css property which gives the fluid scroll and ending bounce effect.

**Comment by dsozzi** [comment] 2018-09-13 07:56
up

**Comment by philipwalton** [comment] 2018-10-21 14:41
Can you link to an example that shows the behavior so it's easier to reproduce? My guess is Safari may be performing the scroll on a compositor thread and not updating the values returned by `getBoundingClientRect()` until the scrolling stops (but that's just a guess, I'd need to see a demo to confirm).

**Comment by shawnnaquin** [comment] 2018-11-16 20:13
I didn't have time to put together a working example. However, on Safari, if the observer's target element's parent is `position:fixed|absolute` the intersectionRatio and isIntersected properties remain falsey. -webkit-overflow-scrolling doesn't seem to be an issue.

tested on Safari V12 OS 10.14 also on an up-to-date iphone SE on mobile safari.

an easy temporary work-around for this is to just use a static or relative position, if possible.

**Comment by aprilmintacpineda** [comment] 2018-12-07 04:08
This happens to me to. I'm using intersectionObserver API for my image lazy loader. But the callback doesn't get call until I release my fingers from the screen. Note that the images doesn't have any position at all. This only happens on ios safari. On safari desktop, I tried playing around and the issue doesn't happen.

**Comment by aprilmintacpineda** [comment] 2018-12-21 02:57
The reason for this are the following codes:

https://github.com/w3c/IntersectionObserver/blob/master/polyfill/intersection-observer.js#L269-L270

![image](https://user-images.githubusercontent.com/21032419/50321893-f2ef6600-050d-11e9-8ae8-66d88b118bb4.png)

On iOS, `scroll event` doesn't fire until scroll if finished. This means that `_checkForIntersections` would only check for intersections when the scroll has finished which happens when the user has removed his finger.

https://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/

**Comment by dsyrstad** [comment] 2018-12-28 20:43
Using 0.5.1, I also have the issue. But I found that setting `io.POLL_INTERVAL = 100;` before observe() - as described in the doc (https://github.com/w3c/IntersectionObserver/blob/master/polyfill/README.md) - works-around this issue on Safari.  I'd certainly like to **not poll** all of the time, but for now it works.

**Comment by maxisam** [comment] 2019-03-05 16:39
test it on ios v11 safari with polyfill
` <script src="https://polyfill.io/v2/polyfill.min.js?features=IntersectionObserver"></script>`

` 'intersectionRatio' in window.IntersectionObserverEntry.prototype ` return false

**Comment by philipwalton** [comment] 2019-04-24 18:28
I'm going to close this as Safari now supports IntersectionObserver natively, and this particular issue seems like a browser limitation that's acceptable since it eventually works. Also, it [sounds like](https://github.com/w3c/IntersectionObserver/issues/315#issuecomment-450424089) using `POLL_INTERVAL` does work, so that's a reasonable workaround for those who need older iOS support.

**Closed by philipwalton** 2019-04-24 18:28 UTC
Labels: polyfill
