### ISSUE TITLE
when trying to make the application  serve-side rendered using angular universal, intersection observer's disconnect method is not defined.

### ISSUE THREAD

**Issue by koundinyab** [w3c/IntersectionObserver#394] opened 2019-09-25 06:48 UTC
Used intersection observer for infinite scroll in angular 8.
`import { Component, OnInit, Input, Output, EventEmitter, ElementRef, ViewChild, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-infinite-scroll',
  template: `<ng-content></ng-content><div #anchor></div>`,
  styleUrls: ['./infinite-scroll.component.scss']
})
export class InfiniteScrollComponent implements OnInit, OnDestroy {

  @Input() options = {};
  @Output() scrolled = new EventEmitter();
  @ViewChild('anchor', {static: true}) anchor: ElementRef<HTMLElement>;

  private observer: IntersectionObserver;

  constructor(private host: ElementRef) { }

  get element() {
    return this.host.nativeElement;
  }

  ngOnInit() {
    const options = {
      root: null,
      ...this.options
    };

    this.observer = new IntersectionObserver(([entry]) => {
      return entry.isIntersecting && this.scrolled.emit();
    }, options);

    this.observer.observe(this.anchor.nativeElement);
  }

  ngOnDestroy() {
    this.observer.disconnect();
  }

}
`
when i do an ng serve, the component works fine.
when i try to serve side render the app using angular universal I get the following error
ERROR ReferenceError: IntersectionObserver is not defined
and 
TypeError: Cannot read property 'disconnect' of undefined
both in server\main.js in the dist folder

Any help is very appreciated. Thank you.

**Comment by philipwalton** [comment] 2019-09-26 02:13
/cc @housseindjirdeh @mgechev

Any idea why the Intersection Observer polyfill wouldn't work in an Angular app using SSR?

**Comment by koundinyab** [comment] 2019-10-10 06:17
@philipwalton , Did you get any chance to look in to this ? If you can suggest a way, i will try to implement and update you. Thanks.

**Comment by mgechev** [comment] 2019-10-10 17:25
The chances are that the issue is not in the `IntersectionObserver` polyfill itself, but in the way it's used with Angular Universal.

@koundinyab could you run the code conditionally and use the `IntersectionObserver` only on the client? Alternatively, could you provide a minimal demo in which we can reproduce the issue?

**Comment by koundinyab** [comment] 2019-10-22 12:17
Hi 
Created a repository with sample code 
https://github.com/koundinyab/intersection-observer-demo
You can do ng serve to see the output and 
npm run build:ssr && npm run serve:ssr
to see the error for universal.
<img width="960" alt="iodemo-error" src="https://user-images.githubusercontent.com/55478800/67284789-e7851680-f4f3-11e9-877a-f584849e2526.png">

Please let me know if implementation can be changed to make it work. 
Much thanks.

**Comment by koundinyab** [comment] 2019-11-01 10:24
@mgechev  Any update please

**Comment by ericjoy94** [comment] 2020-01-16 12:32
I am facing the same issue with the disconnect(). I have implemented it in server side rendered React application.
the component works fine when running on development but when I create a production build, it complains about the disconnect().

Following is my implementation
 componentDidMount() {
    const { src } = this.props;
    this.observer = new IntersectionObserver(
      entries => {
        entries.forEach(entry => {
          const { isIntersecting } = entry;
          if (isIntersecting) {
            this.element.src = src;
            this.observer = this.observer.disconnect();
          }
        });
      },
      {
        root: document.querySelector('.swipe'),
        threshold: [0, 0.25, 0.5, 0.75, 1],
        rootMargin: '10px',
      }
    );
    this.observer.observe(this.element);

I have added a ref on the this.element which is an <img  />

**Comment by gergobergo** [comment] 2020-04-16 09:15
> /cc @housseindjirdeh @mgechev
> 
> Any idea why the Intersection Observer polyfill wouldn't work in an Angular app using SSR?

In my experience the problem is that at the end the polyfill reference to the `window` object and on server side we don't have `window` just `global`, so It won't find any instance of the `IntersectionObserver`.

https://github.com/w3c/IntersectionObserver/blob/master/polyfill/intersection-observer.js#L880

**Comment by pranavkumar389** [comment] 2021-12-01 09:44
Any update on this?

**Comment by ahmetrukenboyaci** [comment] 2022-02-04 12:29
This works for me and can be helpful:

When the app is rendered on server side, observer callback cannot be found. Because observer callback is executed by browser. To handle this issue, observer should be created conditional like:


if (typeof window !== 'undefined') {
    this.observer = new IntersectionObserver(([entry]) => {
         return entry.isIntersecting && this.scrolled.emit();
    }, options);

    this.observer.observe(this.anchor.nativeElement);
}

**Comment by miketaylr** [comment] 2022-06-11 11:51
> When the app is rendered on server side, observer callback cannot be found. Because observer callback is executed by browser.

This is correct. I recommend we close this issue since server-side environments aren't supported by the polyfill.

**Closed by miketaylr** 2022-06-11 11:51 UTC
Labels: polyfill
