### ISSUE TITLE
IntersectionObserver provide setOptions API

### ISSUE THREAD

**Issue by aMiing** [w3c/IntersectionObserver#490] opened 2022-01-25 11:51 UTC
I hope to provide an interface to change options, because when the page size changes, I want to change rootmargin.
because I want to listen to a fixed size window container.

**Comment by miketaylr** [comment] 2022-06-09 23:33
This is a dupe of https://github.com/w3c/IntersectionObserver/issues/428, but thanks for the issue.

**Closed by miketaylr** 2022-06-09 23:33 UTC
Labels: enhancement
